#config_version=5
mode:
  priority: 600
  start_events: game_will_end
  stop_events: move_to_highscore
  use_wait_queue: true
  game_mode: false

event_player: 
  slide_gameovervideo_removed: move_to_highscore

slide_player:
  game_ending:
    gameovervideo:
      target: lcd
      expire: 2s


slides:
  gameovervideo:
    widgets:
      - type: video
        video: linkdyingvideo
        width: 1280
        height: 720