#config_version=5

mode: 
  start_events: slide_darkworld2_slide_active
  stop_events: game_ending, start_ganon_battle
  priority: 1100
  restart_on_next_ball: true

event_player:

  darkworld2_abyss_hit{current_player.total_item_count == 9}: start_ganon_2ball, start_ganon_battle
  darkworld2_abyss_hit{current_player.total_item_count == 10}: start_ganon_3ball, start_ganon_battle
  darkworld2_abyss_hit{current_player.total_item_count < 8}: start_ganon_battle
  darkworld2_abyss_hit{current_player.total_item_count == 8}: start_ganon_battle


  darkworld_shop_hit: start_shop_mode

shots:
  darkworld2_abyss:
    switch: s_abyss
    profile: darkworld2_abyss_profile

  darkworld_shop:
    switch: s_modestart
    profile: darkworld_shop_profile

shot_profiles:

  darkworld2_abyss_profile:
    states:
      - name: ready
        show: darkworld2_abyss_lit
        sync_ms: 150
        loops: -1
        speed: 5
      - name: lit
        show: darkworld2_abyss_hit

  darkworld_shop_profile:
    states:
      - name: ready
        show: darkworld_shop_lit
        sync_ms: 150
        loops: -1
        speed: 5
      - name: lit
        show: darkworld_shop_hit

