#config_version=5

mode: 
  start_events: slide_darkworld2_slide_active
  stop_events: game_ending, start_ganon_battle
  priority: 1100
  restart_on_next_ball: true

event_player:
  darkworld2_abyss_hit{current_player.total_item_count == 8}: start_ganon_2ball, start_ganon_battle
  darkworld2_abyss_hit{current_player.total_item_count == 10}: start_ganon_3ball, start_ganon_battle
  darkworld_shop_hit: start_shop_mode

shots:
  darkworld2_abyss:
    switch: s_abyss


  darkworld_shop:
    switch: s_modestart


