#config_version=5


mode:
  start_events: ball_starting
  stop_events: game_ending
  priority: 100
  # restart_on_next_ball: true


event_player: 
  mode_item_tracker_started: update_item_tracker
  increment_item_tracker: update_item_tracker|10ms

  play_treasure_sfx{device.counters.item_counter.value==1}: boomerang_found
  play_treasure_sfx{device.counters.item_counter.value==2}: bow_found
  play_treasure_sfx{device.counters.item_counter.value==3}: moonpearl_found
  play_treasure_sfx{device.counters.item_counter.value==4}: mirror_found

  update_item_tracker{current_player.item_count ==1 }: set_item1_lightshow
  update_item_tracker{current_player.item_count ==2 }: set_item2_lightshow
  update_item_tracker{current_player.item_count ==3 }: set_item3_lightshow
  update_item_tracker{current_player.item_count ==4 }: set_item4_lightshow
  update_item_tracker{current_player.item_count ==5 }: set_item5_lightshow

  boomerang_found{current_player.boomerang_count < 1}: increment_item_tracker
  bow_found{current_player.bow_count < 1}: increment_item_tracker
  moonpearl_found{current_player.moonpearl_count < 1}: increment_item_tracker
  mirror_found{current_player.mirror_count < 1}: increment_item_tracker

  logicblock_hookshot_counter_complete: hookshot_found
  logicblock_hammer_counter_complete: hammer_found
  logicblock_flipper_counter_complete: flippers_found
  logicblock_bluemail_counter_complete: bluemail_found
  logicblock_redshield_counter_complete: redshield_found

  hookshot_found{current_player.hookshot_count < 1}: set_hookshot_show
  hammer_found{current_player.hammer_count < 1}: set_hammer_show
  flippers_found{current_player.flipper_count < 1}: set_flippers_show
  bluemail_found{current_player.bluemail_count < 1}: set_bluemail_show
  redshield_found{current_player.redshield_count < 1}: set_redshield_show

  update_item_tracker{current_player.hookshot_count > 0 }: set_hookshot_show
  update_item_tracker{current_player.hammer_count > 0 }: set_hammer_show
  update_item_tracker{current_player.flippers_count > 0 }: set_flippers_show
  update_item_tracker{current_player.bluemail_count > 0 }: set_bluemail_show
  update_item_tracker{current_player.redshield_count > 0 }: set_redshield_show



variable_player:
  increment_item_tracker:
    item_count: 1
  boomerang_found:
    boomerang_count: 1
  bow_found:
    bow_count: 1
  moonpearl_found:
    moonpearl_count: 1
  mirror_found:
    mirror_count: 1
  hookshot_found:
    hookshot_count: 1
  hammer_found:
    hammer_count: 1
  flippers_found:
    flipper_count: 1
  bluemail_found:
    bluemail_count: 1
  redshield_found:
    redshield_count: 1




sound_player:
  hookshot_found: treasure_sfx2
  hammer_found: treasure_sfx2
  flippers_found: treasure_sfx2
  bluemail_found: treasure_sfx2
  redshield_found: treasure_sfx2

counters:
  item_counter:
    count_events: play_treasure_sfx
    count_complete_value: 4
    reset_on_complete: false
    persist_state: true

  hookshot_counter:
    count_events: sw_ramp_hit
    count_complete_value: 60
    reset_on_complete: false
    persist_state: true

  hammer_counter:
    count_events: sw_drop
    count_complete_value: 30
    reset_on_complete: false
    persist_state: true

  flipper_counter:
    count_events: sw_jets
    count_complete_value: 100
    reset_on_complete: false
    persist_state: true

  bluemail_counter:
    count_events: sw_spinner
    count_complete_value: 200
    reset_on_complete: false
    persist_state: true

  redshield_counter:
    count_events: sw_slingshot
    count_complete_value: 35
    reset_on_complete: false
    persist_state: true

show_player:
  set_item1_lightshow:
    lamp_lit:
      loops: -1

  set_item2_lightshow:
    boomerang_lit:
      loops: -1

  set_item3_lightshow:
    bow_lit:
      loops: -1

  set_item4_lightshow:
    moonpearl_lit:
      loops: -1

  set_item5_lightshow:
    mirror_lit:
      loops: -1

  set_hookshot_show:
    hookshot_lit:
      loops: -1

  set_hammer_show:
    hammer_lit:
      loops: -1

  set_flippers_show:
    flippers_lit:
      loops: -1

  set_bluemail_show:
    bluemail_lit:
      loops: -1

  set_redshield_show:
    redshield_lit:
      loops: -1

  slide_redshieldvideo_removed:
    redshield_found_slide:
      loops: 0

  slide_bluemailvideo_removed:
    bluemail_found_slide:
      loops: 0

  slide_flippervideo_removed:
    flippers_found_slide:
      loops: 0

  slide_hammervideo_removed:
    hammer_found_slide:
      loops: 0

  slide_hookshotvideo_removed:
    hookshot_found_slide:
      loops: 0

  slide_item2award_removed:
    boomerang_found_slide:
      loops: 0

  slide_item3award_removed:
    bow_found_slide:
      loops: 0

  slide_item4award_removed:
    moonpearl_found_slide:
      loops: 0

  slide_item5award_removed:
    mirror_found_slide:
      loops: 0