#config_version=5
mode:
  priority: 500
  start_events: game_ending, start_high_score, move_to_highscore
  use_wait_queue: true


sound_player:
  high_score_enter_initials: 
    highscore:
      action: play
      loops: 1
  # mode_high_score_stopping:
  #   highscore:
  #     action: stop
  #     fade_out: 2s
  sw_left_flipper: menu_cursor
  sw_right_flipper: menu_cursor
  sw_start: menu_select




high_score:
  _overwrite: True
  enter_initials_timeout: 90
  award_slide_display_time: 4s 
  categories: !!omap
  - score:
      - HYRULE CHAMPION
      - HIGH SCORE 1
      - HIGH SCORE 2
      - HIGH SCORE 3
      - HIGH SCORE 4
  defaults:
    score:
      - W: 9
      - SEF: 6
      - JAM: 3
      - JF: 2
      - Test: 1

# optional: change the slides (you can omit all the following)
slide_player:
  _overwrite: True
  high_score_enter_initials: high_score_enter_initials_mine
  high_score_award_display: high_score_award_display_mine

      




slides:

  high_score_enter_initials_mine:
    - type: text
      style: hyruletext
      font_size: 120
      text: (award)
      color: gold
      x: middle
      y: middle+300

    - type: text_input
      initial_char: A
      dynamic_x: false
      key: high_score
      style: hyruletext
      font_size: 160
      max_chars: 8
      x: middle
      y: middle-175
      shift_left_event: sw_left_flipper
      shift_right_event: sw_right_flipper
      select_event: sw_start
      color: gold

    - type: text
      style: hyruletext
      text: '<       >'
      font_size: 120
      x: middle
      y: middle-200
      color: gold


    - type: text
      text: ''
      key: high_score
      font_size: 80
      style: hyruletext
      x: middle
      y: middle
      color: gold
      animations:
        show_slide:
        - property: opacity
          value: 1
          duration: 0.5s
          easing: in_out_quint
        - property: opacity
          value: 0
          duration: 0.5s
          repeat: true
          easing: in_out_quint

  high_score_award_display_mine:
    - type: text
      text: (player_name)
      font_size: 120
      style: hyruletext
      anchor_y: middle
      anchor_x: middle
      x: middle
      y: middle
      color: gold
      animations:
        show_slide:
        - property: opacity
          value: 1
          duration: 0.05s
        - property: opacity
          value: 0
          duration: 0.05s
          repeat: true
    - type: text
      text: (award)
      font_size: 120
      style: hyruletext
      x: middle
      y: middle+250
      color: gold
    - type: text
      text: (value)
      style: hyruletext
      x: middle
      y: middle-250
      color: gold
      font_size: 120
      number_grouping: true
      min_digits: 1

