#config_version=5
mode:
  start_events: ball_starting
  stop_events: game_ending
  priority: 100

event_player:
  eopto_hit: left_orbit_made
  lopto_hit: right_orbit_made
  modestartmade_hit{current_player.initial_mode_start < 1}: begin_escape
  mode_base_started{current_player.initial_slide_and_music < 1}: start_initial_slide_and_music|10ms

shots:
  modestartmade:
    switch: s_modestart


variable_player:
  modestartmade_hit:
    initial_mode_start: 1   # adds 1 to the player's "initial_mode_start" variable

  start_initial_slide_and_music:
    initial_slide_and_music: 1  # adds 1 to the player's "initial_slide_and_music" variable




slide_player:
  mode_base_started: slide_2
  player_added:
    slide_3:
      expire: 2s
      priority: 1
  ball_live_added: ball_added


sound_player:
  sw_inlane: inlanefx
  sw_jets: jets
  powerup: charge
  sw_drop: shatter
  sw_heart: heart
  sw_flip: flippool
  sw_slingshot: slingpool
  s_left_outlane_active: linkfall
  s_right_outlane_active: linkfall
  skillshot_failed: error

sound_pools:
  flippool:
    load: preload
    type: random
    track: sfx
    sounds: 
      - sword1|2
      - sword2|2
      - swordsilence|6
  slingpool:
    load: preload
    type: random
    track: sfx
    sounds:
      - slingshot|7
      - enemykill|3





coil_player:
  s_optoz1_active:
    crane:
      action: pulse

sequence_shots:
  eopto:
    switch_sequence: s_optoe s_optol
    sequence_timeout: 1s
  lopto:
    switch_sequence: s_optol s_optoe
    sequence_timeout: 1s



show_player:
  mode_base_started:
    escape_mode_flash:
      loops: -1
      speed: 3
    gi:
      loops: -1

  bonus_start:
    ball_end:
      loops: 0
      speed: 15


  mode_2ballqualifier_started:
    escape_mode_flash:
      action: stop

  mode_skill_shot_started:
    skillshot_timing_crawl:
      loops: -1
      speed: 4
  skillshot_heart_award:
    skillshot_timing_crawl:
      action: stop
    skillshot_award_flash:
      loops: 7
      speed: 8
      show_tokens:
        award_led: l_plungerlane3
        award_color: red
  skillshot_ballsave_award:
    skillshot_timing_crawl:
      action: stop
    skillshot_award_flash:
      loops: 7
      speed: 8
      show_tokens:
        award_led: l_plungerlane2
        award_color: orange
  skillshot_rupee_award:
    skillshot_timing_crawl:
      action: stop
    skillshot_award_flash:
      loops: 7
      speed: 8
      show_tokens:
        award_led: l_plungerlane1
        award_color: green
  skillshot_failed:
    skillshot_timing_crawl:
      action: stop

widget_player:
  mode_base_started:
    zelda_fili_border:
      slide: slide_2
      widget_settings:
        z: 2
        x: middle
        y: middle
    transparentbluependant:
      slide: slide_2
      widget_settings:
        z: 3
        x: middle
        y: 550
    transparentgreenpendant:
      slide: slide_2
      widget_settings:
        z: 3
        x: middle-90
        y: 525
    transparentredpendant:
      slide: slide_2
      widget_settings:
        z: 3
        x: middle+85
        y: 525
    transparentcrystal1:
      slide: slide_2
      widget_settings:
        z: 3
        x: middle-150
        y: 135
    transparentcrystal2:
      slide: slide_2
      widget_settings:
        z: 3
        x: middle-100
        y: 135
    transparentcrystal3:
      slide: slide_2
      widget_settings:
        z: 3
        x: middle-50
        y: 135
    transparentcrystal4:
      slide: slide_2
      widget_settings:
        z: 3
        x: middle
        y: 135
    transparentcrystal5:
      slide: slide_2
      widget_settings:
        z: 3
        x: middle+50
        y: 135
    transparentcrystal6:
      slide: slide_2
      widget_settings:
        z: 3
        x: middle+100
        y: 135
    transparentcrystal7:
      slide: slide_2
      widget_settings:
        z: 3
        x: middle+150
        y: 135
  first_pendant_found:
    greenpendant:
      slide: slide_2
      widget_settings:
        z: 4
        x: middle-90
        y: 525
  second_pendant_found:
    bluependant:
      slide: slide_2
      widget_settings:
        z: 4
        x: middle
        y: 550
  third_pendant_found:
    redpendant:
      slide: slide_2
      widget_settings:
        z: 4
        x: middle+85
        y: 525
  maiden_1_rescued:
    crystal1:
      slide: slide_2
      widget_settings:
        z: 4
        x: middle-150
        y: 135
  maiden_2_rescued:
    crystal2:
      slide: slide_2
      widget_settings:
        z: 4
        x: middle-100
        y: 135
  maiden_3_rescued:
    crystal3:
      slide: slide_2
      widget_settings:
        z: 4
        x: middle-50
        y: 135
  maiden_4_rescued:
    crystal4:
      slide: slide_2
      widget_settings:
        z: 4
        x: middle
        y: 135
  maiden_5_rescued:
    crystal5:
      slide: slide_2
      widget_settings:
        z: 4
        x: middle+50
        y: 135
  maiden_6_rescued:
    crystal6:
      slide: slide_2
      widget_settings:
        z: 4
        x: middle+100
        y: 135
  maiden_7_rescued:
    crystal7:
      slide: slide_2
      widget_settings:
        z: 4
        x: middle+150
        y: 135
widgets:
  zelda_fili_border:
  - type: image
    image: zelda_fili
  transparentbluependant:
  - type: image
    image: transparentbluependant
  transparentgreenpendant:
  - type: image
    image: transparentgreenpendant
  transparentredpendant:
  - type: image
    image: transparentredpendant
  greenpendant:
  - type: image
    image: greenpendant
  bluependant:
  - type: image
    image: bluependant
  redpendant:
  - type: image
    image: redpendant
  transparentcrystal1:
  - type: image
    image: transparentcrystal1
  transparentcrystal2:
  - type: image
    image: transparentcrystal2
  transparentcrystal3:
  - type: image
    image: transparentcrystal3
  transparentcrystal4:
  - type: image
    image: transparentcrystal4
  transparentcrystal5:
  - type: image
    image: transparentcrystal5
  transparentcrystal6:
  - type: image
    image: transparentcrystal6
  transparentcrystal7:
  - type: image
    image: transparentcrystal7
  crystal1:
  - type: image
    image: crystal1
  crystal2:
  - type: image
    image: crystal2
  crystal3:
  - type: image
    image: crystal3
  crystal4:
  - type: image
    image: crystal4
  crystal5:
  - type: image
    image: crystal5
  crystal6:
  - type: image
    image: crystal6
  crystal7:
  - type: image
    image: crystal7




slides:

  slide_2:
  - type: text
    text: (score)
    number_grouping: true
    min_digits: 2
    font_size: 244
    style: hyruletext
    x: center 
    y: center-50
  - type: text
    text: PLAYER (number)
    z: 4
    y: 50
    x: 160
    style: hyruletext
    font_size: 60
    color: black
  - type: text
    text: BALL (ball)
    style: hyruletext
    color: black
    z: 4
    x: 1160
    y: 50
    font_size: 60

  slide_3:
  - type: text
    text: PLAYER (num) ADDED
    style: hyruletext
    font_size: 144
