#config_version=5
mode:
  start_events: ball_starting
  stop_events: game_ending
  priority: 100

event_player:
  eopto_hit: left_orbit_made
  lopto_hit: right_orbit_made
  modestartmade_hit{current_player.initial_mode_start < 1}: begin_escape
  mode_base_started{current_player.initial_slide_and_music < 1}: start_initial_slide_and_music|10ms

shots:
  modestartmade:
    switch: s_modestart


variable_player:
  modestartmade_hit:
    initial_mode_start: 1   # adds 1 to the player's "initial_mode_start" variable

  start_initial_slide_and_music:
    initial_slide_and_music: 1  # adds 1 to the player's "initial_slide_and_music" variable




slide_player:
  mode_base_started: slide_2
  player_added:
    slide_3:
      expire: 2s
      priority: 1
  ball_live_added: ball_added


sound_player:
  sw_inlane: inlanefx
  sw_jets: jets
  powerup: charge
  sw_drop: shatter
  sw_heart: heart
  sw_flip: flippool
  sw_slingshot: slingpool
  s_left_outlane_active: linkfall
  s_right_outlane_active: linkfall

sound_pools:
  flippool:
    load: preload
    type: random
    track: sfx
    sounds: 
      - sword1|2
      - sword2|2
      - swordsilence|6
  slingpool:
    load: preload
    type: random
    track: sfx
    sounds:
      - slingshot|7
      - enemykill|3





coil_player:
  s_optoz1_active:
    crane:
      action: pulse

sequence_shots:
  eopto:
    switch_sequence: s_optoe s_optol
    sequence_timeout: 1s
  lopto:
    switch_sequence: s_optol s_optoe
    sequence_timeout: 1s



show_player:
  mode_base_started:
    escape_mode_flash:
      loops: -1
      speed: 3
    gi:
      loops: -1

  ball_ending:
    ball_end:
      loops: 0
      speed: 15
      block_queue: yes

  mode_2ballqualifier_started:
    escape_mode_flash:
      action: stop

  mode_skill_shot_started:
    skillshot_timing_crawl:
      loops: -1
      speed: 4
  skillshot_heart_award:
    skillshot_timing_crawl:
      action: stop
    skillshot_award_flash:
      loops: 7
      speed: 8
      show_tokens:
        award_led: l_plungerlane3
        award_color: red
  skillshot_ballsave_award:
    skillshot_timing_crawl:
      action: stop
    skillshot_award_flash:
      loops: 7
      speed: 8
      show_tokens:
        award_led: l_plungerlane2
        award_color: orange
  skillshot_rupee_award:
    skillshot_timing_crawl:
      action: stop
    skillshot_award_flash:
      loops: 7
      speed: 8
      show_tokens:
        award_led: l_plungerlane1
        award_color: green
  skillshot_failed:
    skillshot_timing_crawl:
      action: stop


slides:

  slide_2:
  - type: text
    text: (score)
    number_grouping: true
    min_digits: 2
    font_size: 288
    style: hyruletext
  - type: text
    text: PLAYER (number)
    anchor_y: bottom
    anchor_x: left
    style: hyruletext
    x: left
    y: bottom
    font_size: 60
  - type: text
    text: BALL (ball)
    anchor_y: bottom
    anchor_x: right
    style: hyruletext
    x: right
    y: bottom
    font_size: 60

  slide_3:
  - type: text
    text: PLAYER (num) ADDED
    style: hyruletext
    font_size: 144
