#config_version=5

mode: 
  start_events: start_ganon_battle  
  stop_events: mode_final_hold_started
  priority: 3000
  # restart_on_next_ball: true


event_player:
  ganon_lane_complete{current_player.ganon_lane_count == 1}: ganon_lane1_video
  ganon_lane_complete{current_player.ganon_lane_count == 2}: ganon_lane2_video
  ganon_lane_complete{current_player.ganon_lane_count == 3}: ganon_lane3_video
  ganon_lane_complete{current_player.ganon_lane_count == 4}: ganon_lane4_video
  ganon_lane_complete{current_player.ganon_lane_count == 5}: activate_final_blow
  final_blow_final_blow_profile_ready_hit: game_over_zelda

  ganon_z4_ganon_z4_profile_ready_hit: z_lane_complete ganon_lane_complete
  ganon_e3_ganon_e3_profile_ready_hit: e_lane_complete ganon_lane_complete
  ganon_l3_ganon_l3_profile_ready_hit: l_lane_complete ganon_lane_complete
  ganon_d3_ganon_d3_profile_ready_hit: d_lane_complete ganon_lane_complete
  ganon_a4_ganon_a4_profile_ready_hit: a_lane_complete ganon_lane_complete

ball_saves:
  final_ballsave:
    active_time: 20s
    hurry_up_time: 6s
    grace_period: 2s
    enable_events: final_blow_hit
    auto_launch: no
    balls_to_save: 1
    only_last_ball: true



variable_player:
  ganon_z4_ganon_z4_profile_ready_hit:
    ganon_lane_count: 1
  ganon_e3_ganon_e3_profile_ready_hit:
    ganon_lane_count: 1
  ganon_l3_ganon_l3_profile_ready_hit:
    ganon_lane_count: 1
  ganon_d3_ganon_d3_profile_ready_hit:
    ganon_lane_count: 1
  ganon_a4_ganon_a4_profile_ready_hit:
    ganon_lane_count: 1
  final_blow_hit:
    survived_ganon: 1

shots:
  ganon_z1:
    switch: s_optoz1
    start_enabled: true
    disable_events: ganon_z1_ready_hit
    restart_events: reset_ganon_shots
    profile: ganon_z1_profile

  ganon_z2:
    switch: s_optoz1
    enable_events: ganon_z1_ready_hit
    disable_events: ganon_z2_ready_hit
    reset_events: reset_ganon_shots
    profile: ganon_z2_profile


  ganon_z3:
    switch: s_optoz1
    enable_events: ganon_z2_ready_hit
    disable_events: ganon_z3_ready_hit
    reset_events: reset_ganon_shots
    profile: ganon_z3_profile

  ganon_z4:
    switch: s_optoz1
    enable_events: ganon_z3_ready_hit
    reset_events: reset_ganon_shots
    profile: ganon_z4_profile

##the next 6 shots are giving issues, all completing one shot per lane
  ganon_e1:
    hit_events: ganon_e_sequence_hit
    start_enabled: true
    disable_events: ganon_e1_hit
    reset_events: restart_ganon_shots
    profile: ganon_e1_profile

  ganon_e2:
    hit_events: ganon_e_sequence_hit
    enable_events: ganon_e1_ready_hit
    disable_events: ganon_e2_hit
    reset_events: restart_ganon_shots
    profile: ganon_e2_profile


  ganon_e3:
    hit_events: ganon_e_sequence_hit
    enable_events: ganon_e2_ready_hit
    reset_events: restart_ganon_shots
    profile: ganon_e3_profile


  ganon_l1:
    hit_events: ganon_l_sequence_hit
    start_enabled: true
    disable_events: ganon_l1_hit
    reset_events: restart_ganon_shots
    profile: ganon_l1_profile

  ganon_l2:
    hit_events: ganon_l_sequence_hit
    enable_events: ganon_l1_ready_hit
    disable_events: ganon_l2_hit
    reset_events: restart_ganon_shots
    profile: ganon_l2_profile


  ganon_l3:
    hit_events: ganon_l_sequence_hit
    enable_events: ganon_l2_ready_hit
    reset_events: restart_ganon_shots
    profile: ganon_l3_profile


  ganon_d1:
    switch: s_optod
    start_enabled: true
    disable_events: ganon_d1_ready_hit
    restart_events: reset_ganon_shots
    profile: ganon_d1_profile

  ganon_d2:
    switch: s_optod
    enable_events: ganon_d1_ready_hit
    disable_events: ganon_zd2_ready_hit
    reset_events: reset_ganon_shots
    profile: ganon_d2_profile


  ganon_d3:
    switch: s_optod
    enable_events: ganon_d2_ready_hit
    reset_events: reset_ganon_shots
    profile: ganon_d3_profile

  ganon_a1:
    switch: s_optoa
    start_enabled: true
    disable_events: ganon_za_ready_hit
    restart_events: reset_ganon_shots
    profile: ganon_a1_profile

  ganon_a2:
    switch: s_optoa
    enable_events: ganon_a1_ready_hit
    disable_events: ganon_a2_ready_hit
    reset_events: reset_ganon_shots
    profile: ganon_a2_profile


  ganon_a3:
    switch: s_optoa
    enable_events: ganon_a2_ready_hit
    disable_events: ganon_a3_ready_hit
    reset_events: reset_ganon_shots
    profile: ganon_a3_profile

  ganon_a4:
    switch: s_optoa
    enable_events: ganon_a3_ready_hit
    reset_events: reset_ganon_shots
    profile: ganon_a4_profile

  final_blow:
    hit_events: final_blow_sequence_hit
    enable_events: activate_final_blow
    profile: final_blow_profile
    reset_events: activate_final_blow


sequence_shots:
  final_blow_sequence:
    switch_sequence: s_optoz1 s_cranehole
    sequence_timeout: 3s
  ganon_e_sequence:
    switch_sequence: s_optoe s_optol
    sequence_timeout: 2s
  ganon_l_sequence:
    switch_sequence: s_optol s_optoe
    sequence_timeout: 2s

# accruals:

#   # z_lane:
#   #   events:
#   #     - ganon_z1_hit
#   #     - ganon_z2_hit
#   #     - ganon_z3_hit
#   #     - ganon_z4_hit
#   #   events_when_complete: z_lane_complete,  ganon_lane_complete   #tag light shows and videos to this

#   # e_lane:
#   #   events:
#   #    - ganon_e1_hit
#   #    - ganon_e2_hit
#   #    - ganon_e3_hit
#   #   events_when_complete: e_lane_complete, ganon_lane_complete

#   # l_lane:
#   #   events:
#   #    - ganon_l1_hit
#   #    - ganon_l2_hit
#   #    - ganon_l3_hit
#   #   events_when_complete: l_lane_complete, ganon_lane_complete

#   # d_lane:
#   #   events:
#   #     - ganon_d1_hit
#   #     - ganon_d2_hit
#   #     - ganon_d3_hit
#   #   events_when_complete: d_lane_complete, ganon_lane_complete

#   # a_lane:
#   #   events:
#   #     - ganon_a1_hit
#   #     - ganon_a2_hit
#   #     - ganon_a3_hit
#   #     - ganon_a4_hit
#   #   events_when_complete: a_lane_complete , ganon_lane_complete


#   ganon_accrual:
#     events:
#       - z_lane_complete
#       - e_lane_complete
#       - l_lane_complete
#       - d_lane_complete
#       - a_lane_complete
#     events_when_complete: activate_final_blow

show_player:
  ganon_z1_hit: 
    ganon_left:
      speed: 13
      loops: 0
  ganon_z2_hit: 
    ganon_right:
      speed: 13
      loops: 0
  ganon_z3_hit: 
    ganon_left:
      speed: 13
      loops: 0
  ganon_z4_hit: 
    ganon_right:
      speed: 13
      loops: 0
  ganon_e1_hit: 
    ganon_hit:
      speed: 13
      loops: 0
  ganon_e2_hit: 
    ganon_hit:
      speed: 13
      loops: 0
  ganon_e3_hit: 
    ganon_hit:
      speed: 13
      loops: 0
  ganon_l1_hit: 
    ganon_hit:
      speed: 13
      loops: 0
  ganon_l2_hit: 
    ganon_hit:
      speed: 13
      loops: 0
  ganon_l3_hit: 
    ganon_hit:
      speed: 13
      loops: 0
  ganon_d1_hit: 
    ganon_hit:
      speed: 13
      loops: 0
  ganon_d2_hit: 
    ganon_hit:
      speed: 13
      loops: 0
  ganon_d3_hit: 
    ganon_hit:
      speed: 13
      loops: 0
  ganon_a1_hit: 
    ganon_right:
      speed: 13
      loops: 0
  ganon_a2_hit: 
    ganon_left:
      speed: 13
      loops: 0
  ganon_a3_hit: 
    ganon_right:
      speed: 13
      loops: 0
  ganon_a4_hit: 
    ganon_left:
      speed: 13
      loops: 0



#adjust speed times on these for chaos and to speed up shows as they are near complete
shot_profiles:
  ganon_z1_profile:
    states:
      - name: ready
        show: ganon_z1_lit
        sync_ms: 150
        loops: -1
        speed: 3
      - name: lit
        show: ganon_z1_hit

  ganon_z2_profile:
    states:
      - name: ready
        show: ganon_z2_lit
        sync_ms: 150
        loops: -1
        speed: 3
      - name: lit
        show: ganon_z2_hit
  ganon_z3_profile:
    states:
      - name: ready
        show: ganon_z3_lit
        sync_ms: 150
        loops: -1
        speed: 3
      - name: lit
        show: ganon_z3_hit
  ganon_z4_profile:
    states:
      - name: ready
        show: ganon_z4_lit
        sync_ms: 150
        loops: -1
        speed: 3
      - name: lit
        show: ganon_z4_hit
  ganon_e1_profile:
    states:
      - name: ready
        show: ganon_e1_lit
        sync_ms: 150
        loops: -1
        speed: 3
      - name: lit
        show: ganon_e1_hit
  ganon_e2_profile:
    states:
      - name: ready
        show: ganon_e2_lit
        sync_ms: 150
        loops: -1
        speed: 3
      - name: lit
        show: ganon_e2_hit
  ganon_e3_profile:
    states:
      - name: ready
        show: ganon_e3_lit
        sync_ms: 150
        loops: -1
        speed: 3
      - name: lit
        show: ganon_e3_hit
  ganon_l1_profile:
    states:
      - name: ready
        show: ganon_l1_lit
        sync_ms: 150
        loops: -1
        speed: 3
      - name: lit
        show: ganon_l1_hit
  ganon_l2_profile:
    states:
      - name: ready
        show: ganon_l2_lit
        sync_ms: 150
        loops: -1
        speed: 3
      - name: lit
        show: ganon_l2_hit
  ganon_l3_profile:
    states:
      - name: ready
        show: ganon_l3_lit
        sync_ms: 150
        loops: -1
        speed: 3
      - name: lit
        show: ganon_l3_hit
  ganon_d1_profile:
    states:
      - name: ready
        show: ganon_d1_lit
        sync_ms: 150
        loops: -1
        speed: 3
      - name: lit
        show: ganon_d1_hit
  ganon_d2_profile:
    states:
      - name: ready
        show: ganon_d2_lit
        sync_ms: 150
        loops: -1
        speed: 3
      - name: lit
        show: ganon_d2_hit
  ganon_d3_profile:
    states:
      - name: ready
        show: ganon_d3_lit
        sync_ms: 150
        loops: -1
        speed: 3
      - name: lit
        show: ganon_d3_hit
  ganon_a1_profile:
    states:
      - name: ready
        show: ganon_a1_lit
        sync_ms: 150
        loops: -1
        speed: 3
      - name: lit
        show: ganon_a1_hit
  ganon_a2_profile:
    states:
      - name: ready
        show: ganon_a2_lit
        sync_ms: 150
        loops: -1
        speed: 3
      - name: lit
        show: ganon_a2_hit
  ganon_a3_profile:
    states:
      - name: ready
        show: ganon_a3_lit
        sync_ms: 150
        loops: -1
        speed: 3
      - name: lit
        show: ganon_a3_hit
  ganon_a4_profile:
    states:
      - name: ready
        show: ganon_a4_lit
        sync_ms: 150
        loops: -1
        speed: 3
      - name: lit
        show: ganon_a4_hit


  final_blow_profile:
    states:
      - name: ready
        show: final_blow_lit
        sync_ms: 150
        loops: -1
        speed: 8
      - name: lit
        show: final_blow_hit
        speed: 20
        loops: 4


