#config_version=5
mode:
  priority: 500
  start_events: game_ending
  use_wait_queue: true
  game_mode: false

high_score:
  _overwrite: True
  enter_initials_timeout: 60
  award_slide_display_time: 4s 
  categories: !!omap
  - score:
      - HYRULE CHAMPION
      - HIGH SCORE 1
      - HIGH SCORE 2
      - HIGH SCORE 3
      - HIGH SCORE 4
  defaults:
    score:
      - W: 9
      - SEF: 6
      - JAM: 3
      - JF: 2



# optional: change the slides (you can omit all the following)
slide_player:
  _overwrite: True
  high_score_enter_initials: high_score_enter_initials
  # high_score_award_display: high_score_award_display

slides:
  high_score_enter_initials:
  - type: text
    style: hyruletext
    font_size: 120
    text: (award)
    color: gold
    x: middle
    y: middle+300

  - type: text_input
    initial_char: A
    dynamic_x: false
    key: high_score
    style: hyruletext
    font_size: 120
    max_chars: 3
    x: middle
    y: middle
    shift_left_event: sw_left_flipper
    shift_right_event: sw_right_flipper
    select_event: sw_start
    color: gold

  - type: text
    style: hyruletext
    text: '<       >'
    font_size: 80
    x: middle
    y: middle
    color: gold


  - type: text
    text: ''
    key: high_score
    font_size: 80
    style: hyruletext
    x: middle
    y: middle+75
    color: gold
    animations:
      show_slide:
      - property: opacity
        value: 1
        duration: 0.5s
        easing: in_out_quint
      - property: opacity
        value: 0
        duration: 0.5s
        repeat: true
        easing: in_out_quint

  # high_score_award_display:
  # - type: text
  #   text: (player_name)
  #   font_size: 80
  #   style: hyruletext
  #   anchor_y: middle
  #   anchor_x: middle
  #   x: middle
  #   y: middle
  #   color: 00ff00
  #   animations:
  #     show_slide:
  #     - property: opacity
  #       value: 1
  #       duration: 0.05s
  #     - property: opacity
  #       value: 0
  #       duration: 0.05s
  #       repeat: true
  # - type: text
  #   text: (award)
  #   font_size: 80
  #   style: hyruletext
  #   x: 105
  #   y: 110
  #   color: 0000ff
  # - type: text
  #   text: (value)
  #   style: hyruletext
  #   x: 105
  #   y: 30
  #   color: 4040FF
  #   font_size: 80
  #   number_grouping: true
  #   min_digits: 2