#config_version=5

mode:
  start_events: ball_starting
  priority: 100
  stop_events: game_ending

event_player:
  ball_starting: update_mode_tracker|5ms
  increment_mode_tracker: update_mode_tracker|10ms
  update_mode_tracker{current_player.mode_count ==1 }: set_mode1_lightshow
  update_mode_tracker{current_player.mode_count ==2 }: set_mode2_lightshow
  update_mode_tracker{current_player.mode_count ==3 }: set_mode3_lightshow
  update_mode_tracker{current_player.mode_count ==4 }: set_mode4_lightshow
  update_mode_tracker{current_player.mode_count ==5 }: set_mode5_lightshow
  # update_mode_tracker{current_player.mode_count ==6}: set_mode6_lightshow


variable_player:
  increment_mode_tracker:
    mode_count: 1

show_player:

  mode_2ballqualifier_started:
    mode_show1:
      loops: -1
      speed: 3

  mode_light_world_started:
    mode_show2:
      loops: -1
      speed: 3
    mode_show1:
      action: stop

  mode_lost_woods_started:
    mode_show3:
      loops: -1
      speed: 3
    mode_show2:
      action: stop

  mode_agahnim_multiball_started:
    mode_show4:
      loops: -1
      speed: 3
    mode_show3:
      action: stop

  mode_darkworld_started:
    mode_show5:
      loops: -1
      speed: 3
    mode_show4:
      action: stop

achievements:
  2ballescape_achievement:
    show_tokens:
      leds: l_mode1
    show_when_selected: flash
    show_when_started: flash
    show_when_completed: on
    events_when_started: 2ballescape_achievement_started
    restart_after_stop_possible: true
    events_when_completed: 2ballescape_achievement_completed
    complete_events: mode_light_world_started
    enable_events: mode_2ballqualifier



