#config_version=5

mode:
  start_events: ball_starting
  priority: 100
  stop_events: game_ending

event_player:
  ball_started: update_mode_tracker|5ms
  increment_mode_tracker: update_mode_tracker|10ms
  update_mode_tracker{current_player.mode_count ==1 }: set_mode1_lightshow
  update_mode_tracker{current_player.mode_count ==2 }: set_mode2_lightshow
  update_mode_tracker{current_player.mode_count ==3 }: set_mode3_lightshow
  update_mode_tracker{current_player.mode_count ==4 }: set_mode4_lightshow
  update_mode_tracker{current_player.mode_count ==5 }: set_mode5_lightshow
  update_mode_tracker{current_player.mode_count ==6}: set_mode6_lightshow
  mode_2ballqualifier_started{current_player.mode1_started < 1}: increment_mode_tracker
  mode_light_world_started{current_player.mode2_started < 1}: increment_mode_tracker
  mode_lost_woods_started{current_player.mode3_started < 1}: increment_mode_tracker
  mode_agahnim_multiball_started{current_player.mode4_started < 1}: increment_mode_tracker
  mode_darkworld_started{current_player.mode5_started < 1}: increment_mode_tracker
  mode_ganon_battle_started{current_player.mode6_started <1}: increment_mode_tracker


variable_player:
  increment_mode_tracker:
    mode_count: 1
  mode_2ballqualifier_started:
    mode1_started: 1
  mode_light_world_started:
    mode2_started: 1
  mode_lost_woods_started:
    mode3_started: 1
  mode_agahnim_multiball_started:
    mode4_started: 1
  mode_darkworld_started:
    mode5_started: 1
  mode_ganon_battle_started:
    mode6_started: 1



show_player:

  set_mode1_lightshow:
    mode_show1:
      loops: -1
      speed: 3

  set_mode2_lightshow:
    mode_show2:
      loops: -1
      speed: 3
    mode_show1:
      action: stop

  set_mode3_lightshow:
    mode_show3:
      loops: -1
      speed: 3
    mode_show2:
      action: stop

  set_mode4_lightshow:
    mode_show4:
      loops: -1
      speed: 3
    mode_show3:
      action: stop

  set_mode5_lightshow:
    mode_show5:
      loops: -1
      speed: 3
    mode_show4:
      action: stop

  set_mode6_lightshow:
    mode_show6:
      loops: -1
      speed: 3
    mode_show5:
      action: stop

 


