#config_version=5

mode: 
  start_events: start_lost_woods
  stop_events: master_sword_found, game_ending
  priority: 900
  restart_on_next_ball: true

event_player:
  master_sword_complete: master_sword_found
  lw_pathfound{device.counters.path_counter.value==1}: 8togo
  lw_pathfound{device.counters.path_counter.value==2}: 7togo, lostwoods_path_1_found
  lw_pathfound{device.counters.path_counter.value==3}: 6togo
  lw_pathfound{device.counters.path_counter.value==4}: 5togo
  lw_pathfound{device.counters.path_counter.value==5}: 4togo, lostwoods_path_2_found
  lw_pathfound{device.counters.path_counter.value==6}: 3togo
  lw_pathfound{device.counters.path_counter.value==7}: 2togo
  lw_pathfound{device.counters.path_counter.value==8}: 1togo, lostwoods_path_3_found
  lw_heart_target_ready_hit: lw_pathfound
  lw_middle_drop_target_ready_hit: lw_pathfound
  lw_modestart_outhole_ready_hit: lw_pathfound
  z_ramp_lostwoods_ready_hit: lw_pathfound
  l_ramp_lostwoods_ready_hit: lw_pathfound
  d_ramp_lostwoods_ready_hit: lw_pathfound
  lw_abyss_shot_ready_hit: lw_pathfound
  lostwoods_left_inlane_ready_hit: lw_pathfound
  lw_crane_shot_ready_hit: lw_pathfound

accruals:
  master_sword_accrual:
    events:
     - 8togo
     - 7togo
     - 6togo
     - 5togo
     - 4togo
     - 3togo
     - 2togo
     - 1togo
    events_when_complete: master_sword_complete
    persist_state: true

counters:
  path_counter:
    count_events: lw_pathfound
    count_complete_value: 9
    persist_state: true


shots:
  lw_heart_target:
    switch: s_heart
    profile: lw_heart_target_profile
  lw_middle_drop_target:
    switch: s_droptarget2
    profile: lw_middle_drop_target_profile
  lw_modestart_outhole:
    switch: s_modestart
    profile: lw_modestart_outhole_profile
  z_ramp_lostwoods:
    switch: s_optoz1
    profile: z_ramp_lostwoods_profile
  l_ramp_lostwoods:
    switch: s_optol
    profile: l_ramp_lostwoods_profile
  d_ramp_lostwoods:
    switch: s_optod
    profile: d_ramp_lostwoods_profile
  lw_abyss_shot:
    switch: s_abyss
    profile: lw_abyss_shot_profile
  lostwoods_left_inlane:
    switch: s_left_inlane
    profile: lostwoods_left_inlane_profile
  lw_crane_shot:
    switch: s_cranehole
    profile: lw_crane_shot_profile


shot_profiles:
  lw_heart_target_profile:
    states:
      - name: ready
        show: lw_heart_target_ready
        sync_ms: 500
        speed: 11
        loops: -1
      - name: lit
        show: lw_heart_target_lit

  lw_middle_drop_target_profile:
    states:
      - name: ready
        show: lw_middle_drop_target_ready
        sync_ms: 500
        speed: 11
        loops: -1
      - name: lit
        show: lw_middle_drop_target_lit

  lw_modestart_outhole_profile:
    states:
      - name: ready
        show: lw_modestart_outhole_ready
        sync_ms: 500
        speed: 11
        loops: -1
      - name: lit
        show: lw_modestart_outhole_lit

  z_ramp_lostwoods_profile:
    states:
      - name: ready
        show: z_ramp_lostwoods_ready
        sync_ms: 500
        speed: 11
        loops: -1
      - name: lit
        show: z_ramp_lostwoods_lit

  l_ramp_lostwoods_profile:
    states:
      - name: ready
        show: l_ramp_lostwoods_ready
        sync_ms: 500
        speed: 11
        loops: -1
      - name: lit
        show: l_ramp_lostwoods_lit

  d_ramp_lostwoods_profile:
    states:
      - name: ready
        show: d_ramp_lostwoods_ready
        sync_ms: 500
        speed: 11
        loops: -1
      - name: lit
        show: d_ramp_lostwoods_lit

  lw_abyss_shot_profile:
    states:
      - name: ready
        show: lw_abyss_shot_ready
        sync_ms: 500
        speed: 11
        loops: -1
      - name: lit
        show: lw_abyss_shot_lit

  lostwoods_left_inlane_profile:
    states:
      - name: ready
        show: lostwoods_left_inlane_ready
        sync_ms: 500
        speed: 11
        loops: -1
      - name: lit
        show: lostwoods_left_inlane_lit

  lw_crane_shot_profile:
    states:
      - name: ready
        show: lw_crane_shot_ready
        sync_ms: 500
        speed: 11
        loops: -1
      - name: lit
        show: lw_crane_shot_lit


track_player:
  mode_lost_woods_started:
    music:
      action: set_volume
      volume: 0.3
      fade: 1s

  lostwoods_path_1_found:
    music:
      action: set_volume
      volume: 0.5
      fade: 1s

  lostwoods_path_2_found:
    music:
      action: set_volume
      volume: 0.7
      fade: 1s

  lostwoods_path_3_found:
    music:
      action: set_volume
      volume: 1.0
      fade: 1s


show_player:
  8togo:
    lostwoods_8_togo:
      loops: 0
      priority: 10
  7togo:
    lostwoods_7_togo:
      loops: 0
      priority: 20
  6togo:
    lostwoods_6_togo:
      loops: 0
      priority: 30
  5togo:
    lostwoods_5_togo:
      loops: 0
      priority: 40
  4togo:
    lostwoods_4_togo:
      loops: 0
      priority: 50
  3togo:
    lostwoods_3_togo:
      loops: 0
      priority: 60
  2togo:
    lostwoods_2_togo:
      loops: 0
      priority: 70
  1togo:
    lostwoods_1_togo:
      loops: 0
      priority: 80

variable_player:
  s_heart_hit:
    score: 1 * current_player.multiplier
  s_droptarget2_hit:
    score: 1 * current_player.multiplier
  s_modestart_hit:
    score: 1 * current_player.multiplier
  s_optoz1_hit:
    score: 1 * current_player.multiplier
  s_optod_hit:
    score: 1 * current_player.multiplier
  s_optol_hit:
    score: 1 * current_player.multiplier
  s_abyss_hit:
    score: 1 * current_player.multiplier
  s_left_inlane_hit:
    score: 1 * current_player.multiplier
  s_cranehole_hit:
    score: 1 * current_player.multiplier