#config_version=5


mode:
  start_events: ball_starting
  stop_events: ball_ending
  priority: 100

event_player:
  slide_agahnimstartvideo_removed: release_mastersword

ball_holds:
  modestart:
    balls_to_hold: 1
    hold_devices: bd_modestart
    enable_events: begin_escape
    release_one_events: slide_escape_instructions_removed
    disable_events: slide_escape_instructions_removed

  pulling_the_sword:
    balls_to_hold: 1
    hold_devices: bd_lostwoods
    enable_events: cue_3ball_multi
    release_one_events: slide_agahnimstartvideo_created
    disable_events: release_mastersword

  darkworld_transition:
    balls_to_hold: 1
    hold_devices: bd_lostwoods
    enable_events: agahnim_complete
    release_one_events: slide_darkworldstart_removed
    disable_events: slide_darkworldstart_removed

  darkworld_zelda_rescue_hold:
    balls_to_hold: 1
    hold_devices: bd_abyss
    enable_events: darkworld_zelda_rescue_ready_hit
    release_one_events: slide_darkworld2_slide_removed, slide_darkworld2_slide_removed
    disable_events: slide_darkworld2_slide_removed, slide_darkworld2_slide_removed



