#config_version=5


mode:
  start_events: ball_starting
  stop_events: ball_ending
  priority: 100

event_player:
  slide_agahnimstartvideo_removed: release_mastersword

ball_holds:
  modestart:
    balls_to_hold: 1
    hold_devices: bd_modestart
    enable_events: begin_escape
    release_one_events: slide_escape_instructions_removed
    disable_events: slide_escape_instructions_removed

  enter_the_woods:
    balls_to_hold: 1
    hold_devices: bd_lostwoods
    enable_events: find_master_sword
    release_one_events: slide_lost_woods_instructions_removed
    disable_events: slide_lost_woods_instructions_removed

  pulling_the_sword:
    balls_to_hold: 1
    hold_devices: bd_lostwoods
    enable_events: cue_3ball_multi
    release_one_events: slide_agahnimstartvideo_created
    disable_events: slide_agahnimstartvideo_created

  darkworld_transition:
    balls_to_hold: 1
    hold_devices: bd_cranehole
    enable_events: agahnim_complete
    release_one_events: slide_darkworldstart_removed
    disable_events: slide_darkworldstart_removed

  darkworld_zelda_rescue_hold:
    balls_to_hold: 1
    hold_devices: bd_abyss
    enable_events: darkworld_zelda_rescue_ready_hit
    release_one_events: slide_darkworld2_slide_removed, slide_darkworld2_slide_removed
    disable_events: slide_darkworld2_slide_removed, slide_darkworld2_slide_removed

  shop_hold:
    balls_to_hold: 1
    hold_devices: bd_modestart
    enable_events: mode_darkworld2_started
    release_one_events: exit_shop
    disable_events: exit_shop

  ganon_hold:
    balls_to_hold: 1
    hold_devices: bd_abyss
    enable_events: mode_darkworld2_started
    release_one_events: slide_ganonintro_removed
    disable_events: slide_ganonintro_removed

  # final_blow_hold:
  #   balls_to_hold: 1
  #   hold_devices: bd_cranehole
  #   enable_events: hold_final_ball
  #   release_one_events: slide_finalblowvideo_removed
  #   disable_events: slide_finalblowvideo_removed




