#config_version=5

mode: 
  start_events: find_master_sword
  stop_events: end_lostwoods_starter, game_ending
  priority: 800
  restart_on_next_ball: true



event_player: 
  lost_woods_orbit_hit: start_lost_woods
  mode_lost_woods_starting: end_lostwoods_starter
  timer_town_music_starter_complete: start_town_music


timers:
  town_music_starter:
    start_value: 0
    end_value: 16
    tick_interval: 1s
    direction: up
    control_events:
      - action: start
        event: mode_lost_woods_starter_started




shots:
  lost_woods_orbit:
    switch: s_lostwoods
    profile: lost_woods_profile


shot_profiles:
  lost_woods_profile:
    states:
      - name: ready
        show: lost_woods_profile_ready
        loops: -1
        speed: 4
      - name: lit
        show: lost_woods_profile_lit
        loops: -1
        speed: 10
