#config_version=5
#Zelda

game:
  balls_per_game: 3
  allow_start_with_ball_in_drain: true
  allow_start_with_loose_balls: true

config:
- hardware.yaml
- keyboard.yaml
- videos.yaml

modes:
- attract
- base
- ball_save
- bonus
- extraball
- 2ballqualifier
- 2ballescape
- escapehurryup
- light_world
- lost_woods_starter
- lost_woods
- master_sword_buildup
- agahnim_multiball
- darkworld
- music_player
- video_player
- item_tracker
- slide_tracker
- mode_tracker
- mode_player
- heart_tracker
- bomb_finder
- ball_hold_tracker
- heartmeter
- unusual_show_tracker
- 5waycombotracker
- high_score
- gameoverplayer
- playfield_multiplier
- rupee_finder
- rupee2x_finder
- rupee3x_finder
- bottle_filler
- skill_shot
- skillshot_ballsave
# - attract_carousel
- shop
- ganon_battle
- darkworld2
- game_ender_mode
- final_hold

window:
  title: Legend of Zelda
  height: 720
  width: 1280
  resizable: true
  fullscreen: false
  borderless: false
  exit_on_escape: true


displays:
  lcd:
    height: 720
    width: 1280
    default: true

sound_player:



sound_system:
    master_volume: 1.0
    tracks:
       music:
          simultaneous_sounds: 3
          volume: 0.5
       voice:
          simultaneous_sounds: 1
          volume: 0.7
       sfx:
          simultaneous_sounds: 8
          volume: 0.9


sounds:
  linkhurt1:
    volume: 0.7
  linkhurt2:
    volume: 0.7
  linkhurt3:
    volume: 0.7



assets:
    sounds:
        default:
            load: preload
        music:
            track: music
        sfx:
            track: sfx
        voice:
            track: voice
    videos:
        default:
            load: preload

widget_styles:
  default:
  hyruletext:
    font_name: Triforce
    font_size: 72

shot_profiles:
   tri_state:
       states:
       - name: unlit
         show: off
       - name: lit
         show: flash
       - name: complete
         show: on 
   on_off:
       states:
       - name: unlit
         show: off
       - name: lit
         show: on
   flash:
       states:
       - name: lit
         show: flash
       - name: unlit
         show: off

multiballs:
  s2ballescape_multiball:
    ball_count: 2
    ball_locks: bd_abyss
    ball_count_type: total
    shoot_again: 90s
    enable_events: zelda_2ball_complete
    start_events: multiball_lock_2ballescape_locked_ball
    stop_events: mode_2ballescape_multiball_stopping, 2ballescape_complete
    disable_events: flippers_alive

  agahnim_multiball:
    ball_count: 3
    ball_count_type: total
    shoot_again: 90s
    enable_events: cue_3ball_multi
    start_events: slide_agahnimstartvideo_created
    stop_events: agahnim_complete
    disable_events: agahnim_complete


  ganon_multiball2:
    ball_count: 2
    ball_count_type: total
    shoot_again: 30s
    enable_events: darkworld2_abyss_hit
    start_events: start_ganon_2ball
    stop_events: ganon_defeated
    disable_events: ganon_defeated


  ganon_multiball3:
    ball_count: 3
    ball_count_type: total
    shoot_again: 60s
    enable_events: darkworld2_abyss_hit
    start_events: start_ganon_3ball
    stop_events: ganon_defeated
    disable_events: ganon_defeated



player_vars:
  multiplier:
    value_type: int
    initial_value: 1

  item_count:
    value_type: int
    initial_value: 1

  extraball_heart_count:
    value_type: int
    initial_value: 0

  skillshot_award_count:
    value_type: int
    initial_value: 0

  heart_piece_count:
    value_type: int
    initial_value: 0

  total_item_count:
    value_type: int
    initial_value: 1

  ganon_lane_count:
    value_type: int
    initial_value: 0

  survived_ganon:
    value_type: int
    initial_value: 0

  pendant_count:
    value_type: int
    initial_value: 0

  maiden_count:
    value_type: int
    initial_value: 0

  initial_mode_start_variable:
    value_type: int
    initial_value: 0

  begin_escape_variable:
    value_type: int
    initial_value: 0

  light_world_start_variable:
    value_type: int
    initial_value: 0

  lost_woods_start_variable:
    value_type: int
    initial_value: 0

  agahnim_variable:
    value_type: int
    initial_value: 0

  darkworld_variable:
    value_type: int
    initial_value: 0

  ganonbattle_variable:
    value_type: int
    initial_value: 0

  mode1_qualifier_variable:
    value_type: int
    initial_value: 0

  mode1_variable:
    value_type: int
    initial_value: 0

  mode2_variable:
    value_type: int
    initial_value: 0

  mode2_part2_variable:
    value_type: int
    initial_value: 0

  mode3_variable:
    value_type: int
    initial_value: 0

  mode4_variable:
    value_type: int
    initial_value: 0

  mode5_variable:
    value_type: int
    initial_value: 0

  mode5_part2_variable:
    value_type: int
    initial_value: 0

  mode6_variable:
    value_type: int
    initial_value: 0

  wizard_count:
    value_type: int
    initial_value: 0

  current_attract_slide:
    value_type: int
    initial_value: 1

  agahnim_attack_variable:
    value_type: int
    initial_value: 1

  path_variable:
    value_type: int
    initial_value: 0


  green_pendant_variable:
    value_type: int
    initial_value: 0

  blue_pendant_variable:
    value_type: int
    initial_value: 0

  red_pendant_variable:
    value_type: int
    initial_value: 0
