#config_version=5
keyboard:
  z:
    switch: leftflipperbutton
  x:
    switch: rightflipperbutton
  1:
    switch: trough1
    toggle: true
  2:
    switch: trough2
    toggle: true
  p:
    switch: plungerlane
    toggle: true
  s:
    switch: start
  r:
    switch: s_right_outlane
  q:
    switch: s_left_outlane
  e:
    switch: s_right_inlane
  w:
    switch: s_left_inlane
  n:
    switch: s_rightpop
  9:
    switch: s_leftpop
  t:
    switch: s_toppop
  m:
    switch: s_abyss
  y:
    switch: s_droptarget1
  u: 
    switch: s_droptarget2
  i:
    switch: s_droptarget3
  o: 
    switch: s_heart
  a:
    switch: s_modestart

  d:
    switch: s_optoz1
  f:
    switch: s_optoe
  g:
    switch: s_optol
  h:
    switch: s_optod
  j:
    switch: s_optoa
  k:
    switch: s_lostwoods
  b:
    switch: s_cranehole
  v:
    switch: s_spinner