#config_version=5


mode:
  start_events: ball_starting
  stop_events: game_ending
  priority: 100


extra_balls:
  heart_extra_ball:
    award_events: award_heart_extraball

show_player:
  slide_heart_piece_extraball_removed:
    extra_ball_slide:
      loops: 0