#config_version=5


mode:
  start_events: ball_starting
  stop_events: game_ending
  priority: 100


extra_balls:
  heart_extra_ball:
    award_events: award_heart_extraball  #wizard goal

  item_extra_ball:
    award_events: award_item_extraball  #not wizard goal but still an extraball

  bottle_extra_ball:
    award_events: award_bottle_extraball    #wizard goal

show_player:
  slide_heart_piece_extraball_removed:
    extra_ball_slide:
      loops: 0

  # slide_item_extraball_removed:
  #   extra_ball_slide:
  #     loops: 0
slide_player: 
  slide_item_extraball_removed:  extra_ball_slide

slides:
  extra_ball_slide:
    expire: 3s
    widgets:
    - type: Text
      text: EXTRA BALL
      style: hyruletext
      color: gold
      font_size: 200
      animations:
        pre_show_slide:
          - property: opacity
            value: 0
            duration: .2s
          - property: opacity
            value: 1
            duration: .2s
            repeat: -1