#config_version=5

mode:
  start_events: mode_attract_started
  stop_events: mode_attract_stopped  
  code: mpf.modes.carousel.code.carousel.Carousel
  game_mode: false
  priority: 110

event_player:
  timer_attract_timer1_complete: rightflipperbutton_active
  timer_attract_timer2_complete: restart_timer1


mode_settings:
  selectable_items: hyrulechamp_slide, highscore_slide, previous_game_scores, awesome_slide, awesome_slide2, press_start, mpf_slide, fast_slide, special_thanks_slide, sp_slide, attract_video_slide
  select_item_events: flipper_cancel
  next_item_events: rightflipperbutton_active
  previous_item_events: leftflipperbutton_active


timers:
  attract_timer1:
    start_value: 1
    end_value: 10
    direction: up
    restart_on_complete: true
    control_events:
      - action: start
        event: mode_attract_carousel_started
      - action: restart
        event: restart_timer1
      - action: stop
        event: sw_flip

  attract_timer2:
    start_value: 1
    end_value: 15
    direction: up
    control_events:
      - action: start
        event: sw_flip
      - action: restart
        event: sw_flip

slide_player:
  attract_carousel_hyrulechamp_slide_highlighted: hyrulechamp_slide
  attract_carousel_highscore_slide_highlighted: highscore_slide
  attract_carousel_previous_game_scores_highlighted: previous_game_scores
  attract_carousel_awesome_slide_highlighted: awesome_slide
  attract_carousel_awesome_slide2_highlighted: awesome_slide2
  attract_carousel_press_start_highlighted: press_start
  attract_carousel_mpf_slide_highlighted: mpf_slide
  attract_carousel_fast_slide_highlighted: fast_slide
  attract_carousel_special_thanks_slide_highlighted: special_thanks_slide
  attract_carousel_sp_slide_highlighted: sp_slide
  attract_carousel_attract_video_slide_highlighted: attract_video_slide

widget_player:
  mode_attract_carousel_started:
    player1_score_widget:
      slide: previous_game_scores
      widget_settings:
        z: 2


widgets:
  player1_score_widget:
    - type: text
      text: Player 1
      style: hyruletext
      font_size: 80
      y: 650
      x: 175
    - type: text
      text: (machine|player1_score)
      style: hyruletext
      font_size: 80
      y: 575
      x: 175
      # - type: text
      #   text: Player 2
      #   style: hyruletext
      #   font_size: 80
      #   y: 650
      #   x: 1105
      # - type: text
      #   text: (machine|player2_score)
      #   style: hyruletext
      #   font_size: 80
      #   y: 575
      #   x: 1105
      # - type: text
      #   text: Player 3
      #   style: hyruletext
      #   font_size: 80
      #   y: 150
      #   x: 175
      # - type: text
      #   text: (machine|player3_score)
      #   style: hyruletext
      #   font_size: 80
      #   y: 75
      #   x: 175

slides:
  hyrulechamp_slide:
    widgets:
    - type: text
      text: HYRULE CHAMPION
      style: hyruletext
      font_size: 125
      y: 625
      color: gold
    - type: text
      text: (machine|score1_name)
      style: hyruletext
      font_size: 125
      y: 400
      number_grouping: true
      color: gold 
      animations:
        pre_show_slide:
          - property: opacity
            value: 0
            duration: .5s
          - property: opacity
            value: 1
            duration: .5s
            repeat: -1
    - type: text
      text: (machine|score1_value)
      style: hyruletext
      font_size: 125
      y: 275
      number_grouping: true
      color: gold 
      animations:
        pre_show_slide:
          - property: opacity
            value: 0
            duration: .5s
          - property: opacity
            value: 1
            duration: .5s
            repeat: -1


  highscore_slide:
    widgets:
    - type: text
      text: HIGH SCORES
      style: hyruletext
      font_size: 100
      y: 650
      color: gold
    - type: text
      text: 1. (machine|score2_name) (machine|score2_value)
      style: hyruletext
      font_size: 80
      y: 500
      number_grouping: true
      color: gold 
    - type: text
      text: 2. (machine|score3_name) (machine|score3_value)
      style: hyruletext
      font_size: 80
      y: 400
      number_grouping: true
      color: gold 
    - type: text
      text: 3. (machine|score4_name) (machine|score4_value)
      style: hyruletext
      font_size: 80
      y: 300
      number_grouping: true
      color: gold 
    - type: text
      text: 4. (machine|score5_name) (machine|score5_value)
      style: hyruletext
      font_size: 80
      y: 200
      number_grouping: true
      color: gold 

  previous_game_scores:
    widgets:
      - type: image
        image: final_score_gif
        x: middle
        y: middle


  awesome_slide:
    widgets:
    - type: text
      text: The Legend of Zelda
      style: hyruletext
      font_size: 100
    transition:
       type: push
       duration: 2s
       direction: left

  awesome_slide2:
    widgets:
    - type: text
      text: A Link to the Past
      style: hyruletext
      font_size: 144
    transition:
       type: fade_back
       duration: 3s

  press_start:
    widgets:
    - type: Text
      text: PRESS START
      style: hyruletext
      font_size: 72
      animations:
        pre_show_slide:
          - property: opacity
            value: 0
            duration: .5s
          - property: opacity
            value: 1
            duration: .5s
            repeat: -1

    - type: Text
      text: FREE PLAY
      style: hyruletext
      font_size: 72
      color: green
      y: 10
      anchor_y: bottom
    transition:
       type: move_in
       duration: 1s
       direction: right

  mpf_slide:
    background_color: white
    widgets:
    - type: image
      image: mpf_logo
    transition:
       type: move_in
       duration: 1s
       direction: left

  fast_slide:
    widgets:
    - type: image
      image: fast_logo
    transition:
       type: move_in
       duration: 1s
       direction: left

  special_thanks_slide:
    widgets:
    - type: Text
      text: Special Thanks To
      color: White
      anchor_y: bottom
      style: hyruletext
      font_size: 80
    - type: Text
      text: John Marsh
      style: hyruletext
      font_size: 144
      color: Green
      anchor_y: top

  sp_slide:
    widgets:
    - type: Text
      text: Save Point
      color: red
      anchor_y: bottom
      style: hyruletext
      font_size: 200
    - type: Text
      text: Presents...
      style: hyruletext
      font_size: 200
      color: red
      anchor_y: top
    transition:
       type: move_in
       duration: 1s
       direction: left

  attract_video_slide:
    widgets:
    - type: video
      video: attractvideo
      width: 1280
      height: 720
