#config_version=5


mode: 
  start_events: ball_started{ball==1}
  stop_events: mode_2ballqualifier_started, game_ending, game_ended
  priority: 100
  # stop_on_ball_end: false
  #restart_on_next_ball: true

# event_player:
#   modestartmade_hit: begin_escape


# shots:
#   modestartmade:
#     switch: s_modestart




