#config_version=5


mode: 
  start_events: ball_started{ball==1}
  stop_events: mode_escape_started, game_ending, game_ended
  priority: 100
  # stop_on_ball_end: false



event_player:
  modestartmade_hit: begin_escape



shots:
  modestartmade:
    switch: s_modestart




