#config_version=5

mode:
  start_events: ball_starting
  stop_events: game_ending
  priority: 100

event_player:
  ball_started{current_player.initial_mode_start_variable == 1 and current_player.begin_escape_variable == 0}: initial_music
  ball_started{current_player.begin_escape_variable == 1 and current_player.light_world_start_variable == 0}: mode1_music
  ball_started{current_player.light_world_start_variable == 1 and current_player.mode2_part2_variable == 0}: mode2_music
  ball_started{current_player.mode2_part2_variable == 1 and current_player.lost_woods_start_variable == 0}: mode2_part2_music
  ball_started{current_player.lost_woods_start_variable == 1 and current_player.agahnim_variable == 0}: mode3_music
  ball_started{current_player.agahnim_variable == 1 and current_player.darkworld_variable == 0}: mode4_music
  ball_started{current_player.darkworld_variable == 1 and current_player.darkworld2_variable == 0}: mode5_music
  ball_started{current_player.darkworld2_variable == 1 and curent_player.ganonbattle_variable == 0}: mode5_part2_music
  ball_started{current_player.ganonbattle_variable == 1}: mode6_music

  start_initial_slide_and_music: stop_all_music initial_music|20ms 
  begin_escape: stop_all_music mode1_music|20ms
  mode_light_world_started: stop_all_music mode2_music|20ms
  start_town_music: stop_all_music mode2_part2_music|20ms
  start_lost_woods: stop_all_music mode3_music|20ms
  slide_agahnimstartvideo_created: stop_all_music mode4_music|20ms
  slide_agahnimdefeatedvideo_removed: stop_all_music mode5_music|20ms
  slide_darkworld2_slide_active: stop_all_music mode5_part2_music|20ms
  slide_ganonintro_removed: stop_all_music mode6_music|20ms




variable_player:
  start_initial_slide_and_music:
    initial_mode_start_variable: 1
  begin_escape:
    begin_escape_variable: 1
  mode_light_world_started:
    light_world_start_variable: 1
  start_town_music:
    mode2_part2_variable: 1
  start_lost_woods:
    lost_woods_start_variable: 1
  slide_agahnimstartvideo_created:
    agahnim_variable: 1
  slide_agahnimdefeatedvideo_removed:
    darkworld_variable: 1
  slide_ganonintro_removed:
    ganonbattle_variable: 1

sound_player:

  initial_music:
    timeoffalling:
      action: play
      loops: -1
    rainout:
      loops: 2
      volume: 0.5

  mode1_music:
    hyrulecastle:
      loops: -1
      volume: 0.5
    rainin:
      loops: 1
      volume: 0.5
      fade_out: 2s
    timeoffalling:
      action: stop
      fade_out: 1s
    rainout:
      action: stop
      fade_out: 3s


  mode_escapehurryup_started:
    hyrulecastle:
      action: stop
      fade_out: 1s
    princess_zeldas_rescue:
      loops: -1
      volume: 0.5

  mode_light_world_started:
    princess_zeldas_rescue:
      action: stop
      fade_out: 1s

  mode2_music:
    light_world_theme:
      loops: -1
      volume: 0.5

  light_world_complete:
    light_world_finished:
      action: play
      loops: 0
      volume: 1.0
    light_world_theme:
      action: stop
      fade_out: 1s

  mode2_part2_music:
    town_music:
      action: play
      loops: -1
      volume: 0.5

  mode3_music:
    forest:
      action: play
      loops: -1
      volume: 0.5

    light_world_finished:
      action: stop
      fade_out: 2s

    town_music:
      action: stop
      fade_out: 2s

  mode4_music:
    battle:
      action: play
      loops: -1
      volume: 0.5

  mode5_music:
    battle:
      action: stop
      fade_out: 1s
    darkworld:
      action: play
      loops: -1
      volume: 0.5

  mode5_part2_music:
    darkworld2:
      action: play
      loops: -1
      volume: 0.7
  slide_ganonintro_active:
    darkworld2:
      action: stop
      fade_out: 2s
  mode6_music:
    ganonbattle:
      action: play
      loops: -1
      volume: 1.0


  ball_started{ball==3}:
    low_health:
      action: play
      loops: 7
      fade_out: 0.5s

  play_bomb_sfx: 
    bomb_spots_item:
      action: play
      loops: 0
      volume: 1.0

  play_treasure_sfx:
    treasure_sfx:
      action: play
      loops: 0
      volume: 1.0

  lostwoods_path_1_found:
    lost_woods_correct:
      action: play
      loops: 0
      volume: 1.0

  lostwoods_path_2_found:
    lost_woods_correct:
      action: play
      loops: 0
      volume: 1.0

  lostwoods_path_3_found:
    lost_woods_correct:
      action: play
      loops: 0
      volume: 1.0


  cue_3ball_multi:
    forest:
      action: stop
      fade_out: 2s

  darkworld_zelda_rescue_ready_hit:
    darkworld:
      action: stop
      fade_out: 1s

    darkworld_rescue:
      action: play
      loops: 0
      volume: 0.5

  slide_maiden7_removed:
    darkworld_rescue:
      action: stop
      fade_out: 1s

  final_blow_hit:
    ganonbattle:
      action: stop
      fade_out: 2s

  stop_all_music:
    timeoffalling:
      action: stop
      fade_out: 1s
    hyrulecastle:
      action: stop
      fade_out: 1s
    light_world_theme:
      action: stop
      fade_out: 1s
    town_music:
      action: stop
      fade_out: 1s
    rainout:
      action: stop
      fade_out: 1s
    rainin:
      action: stop
      fade_out: 1s
    forest:
      action: stop
      fade_out: 1s
    battle:
      action: stop
      fade_out: 1s
    darkworld:
      action: stop
      fade_out: 1s
    darkworld2:
      action: stop
      fade_out: 1s
    ganonbattle:
      action: stop
      fade_out: 1s
  bonus_start:
    timeoffalling:
      action: stop
      fade_out: 1s
    hyrulecastle:
      action: stop
      fade_out: 1s
    light_world_theme:
      action: stop
      fade_out: 1s
    town_music:
      action: stop
      fade_out: 1s
    rainout:
      action: stop
      fade_out: 1s
    rainin:
      action: stop
      fade_out: 1s
    forest:
      action: stop
      fade_out: 1s
    battle:
      action: stop
      fade_out: 1s
    darkworld:
      action: stop
      fade_out: 1s
    darkworld2:
      action: stop
      fade_out: 1s
    ganonbattle:
      action: stop
      fade_out: 1s




